myapp/urls.py
from django.urls import path
from .views import store_view, cart_view, checkout_view, updateCart,processOrder

app_name = 'myapp'
urlpatterns = [
    path('', store_view, name='store'),
    path('cart/', cart_view, name='cart'),
    path('checkout/', checkout_view, name='checkout'),
    path('update-cart/', updateCart, name='update_cart'),
    path('process-order/', processOrder, name='process-order'),
]

store/urls.py
from django.contrib import admin
from django.urls import path,include

from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('myapp.urls')),  # Include URLs from your app
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)

myapp/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.


class Customer(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    email = models.EmailField(max_length=254, unique=True)
    name = models.CharField(max_length=150, null=True, blank=True)

    def __str__(self):
        return self.name
    
class Product(models.Model):
    name = models.CharField(max_length=255)
    description = models.TextField(null=True, blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    digital = models.BooleanField(default=False)
    image = models.ImageField(upload_to='products/', blank=True, null=True)
    #stock = models.PositiveIntegerField(default=0)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name
    
    #we use this where no image provide to avoide error
    @property
    def imageUrl(self):
        try:
            url =self.image.url
        except:
            url =''
        return url
    
class Order(models.Model):
    customer = models.ForeignKey(Customer, on_delete=models.SET_NULL ,null=True)
    order_date = models.DateTimeField(auto_now_add=True)
    completed = models.BooleanField(default=False)
    transaction_id = models.CharField(max_length=255, null=True, blank=True)

    def __str__(self):
        return str(self.id)
    
    @property
    def shipping(self):
        shipping = False
        orderitems = self.orderitem_set.all()
        for item in orderitems:
            if item.product.digital == False:
                shipping = True
        return shipping
    
class OrderItem(models.Model):
    order = models.ForeignKey(Order, on_delete=models.SET_NULL,null=True)
    product = models.ForeignKey(Product, on_delete=models.SET_NULL,null=True)
    quantity = models.PositiveIntegerField(default=0)
    price = models.DecimalField(max_digits=10, decimal_places=2,null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.quantity} x {self.product.name} in Order {self.order.id}"
    @property
    def total_price(self):
        return float(self.price) * float(self.quantity)
    
    def save(self, *args, **kwargs):
        if not self.price and self.product:
            self.price = self.product.price  # assumes Product model has `price` field
        super().save(*args, **kwargs)
    
    class Meta:
        verbose_name_plural = 'Order Items'
    

    
class ShippingAddress(models.Model):
    customer = models.ForeignKey(Customer, on_delete=models.SET_NULL, null=True)
    order = models.ForeignKey(Order, on_delete=models.SET_NULL, null=True)
    address= models.CharField(max_length=255, blank=True, null=True)
    # city = models.CharField(max_length=100)
    state = models.CharField(max_length=100)
    zip_code = models.CharField(max_length=20)
    country = models.CharField(max_length=100,null=True,blank=True)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"Shipping Address for Order {self.order.id} by {self.customer.user.username}"

myapp/views.py
from django.shortcuts import render
from .models import Product,Customer, Order, OrderItem,ShippingAddress
from django.http import JsonResponse
import json
import datetime
# Create your views here.


def store_view(request):
    products =Product.objects.all()
    context={
        'products':products
    }   
    return render(request, 'myapp/store.html',context)

def cart_view(request):
    if request.user.is_authenticated:
        customer = Customer.objects.get(user=request.user)
        
        
        order, created = Order.objects.get_or_create(customer=customer, completed=False)
        order_items = OrderItem.objects.filter(order=order)
        total_price = sum(float(item.price) * float(item.quantity) for item in order_items)
        
             
    else:
        order_items = []
    context = {
        'order_items': order_items,
        'order': order if request.user.is_authenticated else None,
        'total_price': total_price if request.user.is_authenticated else 0,
        
    }
        
    return render(request, 'myapp/cart.html', context)

def checkout_view(request):
    if request.user.is_authenticated:
        customer = Customer.objects.get(user=request.user)
        order, created = Order.objects.get_or_create(customer=customer, completed=False)
        order_items = OrderItem.objects.filter(order=order)
        total_price = sum(float(item.price) * float(item.quantity) for item in order_items)
    else:
        order_items = []
    context = {
        'order_items': order_items,
        'order': order if request.user.is_authenticated else None,
        'total_price': total_price if request.user.is_authenticated else 0,
        'shipping':order.shipping if request.user.is_authenticated else False,
    }
    return render(request, 'myapp/checkout.html',context)


def updateCart(request):
    data = json.loads(request.body)
    
    product_id = data['productId']
    action = data['action']
    print('Action:', action)

    customer = Customer.objects.get(user=request.user)
    product = Product.objects.get(id=product_id)

    order,created = Order.objects.get_or_create(customer=customer, completed=False)
    order_item, created = OrderItem.objects.get_or_create(order=order,product=product)

    if action == 'add':
        order_item.quantity += 1
    elif action == 'remove':
        order_item.quantity -= 1
    order_item.save()

    if order_item.quantity <= 0:
        order_item.delete()
    return JsonResponse('Item was added', safe=False)

def processOrder(request):
    transaction_id = datetime.datetime.now().timestamp()
    data = json.loads(request.body)
    print("Received data:", data)

    if request.user.is_authenticated:
        customer = request.user.customer
        order, created = Order.objects.get_or_create(customer=customer, completed=False)

        total = float(data['form']['total_price'])
        print('Total from frontend:', total)

        order_items = OrderItem.objects.filter(order=order)
        total_price = sum(float(item.price) * float(item.quantity) for item in order_items)
        print('Total from database:', total_price)

        if total == total_price:
            print('Total price is correct')
            order.transaction_id = transaction_id
            order.completed = True
            order.save()
            print("Order saved:", order.transaction_id, order.completed)
        else:
            print("Total mismatch. Not saving order.")
        print('Order ID:', order.id)
        print('Completed:', order.completed)
        print('Transaction ID:', order.transaction_id)
  
        if order.shipping:
            ShippingAddress.objects.create(
                customer=customer,
                order=order,
                address=data['shipping-data']['address'],
                state=data['shipping-data']['state'],
                zip_code=data['shipping-data']['zip_code'],
                country=data['shipping-data']['country'],
            )
            print("Shipping address created.")
    else:
        print('User is not authenticated.')

    return JsonResponse('Order processed', safe=False)

myapp/templates/main.html
<!DOCTYPE html>
<html lang="en">
{% load static %}

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'styles/main.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.7/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-LN+7fdVzj6u52u30Kp6M/trliBMCMKTyK833zpbD+pXdCLuTusPj697FH4R/5mcr" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.7/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ndDqU0Gzau9qJ1lfW4pNLlhNTkCfHzAVBReH9diLvGRem5+R9g2FzA8ZGN954O5Q"
        crossorigin="anonymous"></script>
    <title>
        {% block title %}
        e Commerce Website
        {% endblock title %}
    </title>
    <script>
        let user = '{{ request.user }}';
        function getCookie(name) {
            let cookieValue = null;
            if (document.cookie && document.cookie !== '') {
                const cookies = document.cookie.split(';');
                for (let i = 0; i < cookies.length; i++) {
                    const cookie = cookies[i].trim();
                    // Does this cookie string begin with the name we want?
                    if (cookie.substring(0, name.length + 1) === (name + '=')) {
                        cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                        break;
                    }
                }
            }
            return cookieValue;
        }
        const csrftoken = getCookie('csrftoken');

        function getCookie(name) {
            let cookieArray = document.cookie.split(';');
            for (let i = 0; i < cookieArray.length; i++) {
                let cookiePair = cookieArray[i].trim().split('=');
                if (cookiePair[0].trim() === name) {
                    return decodeURIComponent(cookiePair[1]);
                }
            }
            return null;
        }
        let cart = JSON.parse(getCookie('cart'))
        console.log('cart', cart);
        console.log(document.cookie);
        if (cart === null || cart === undefined) {
            cart = {};
            document.cookie = 'cart=' + JSON.stringify(cart) + '; path=/;';
            console.log('Cart initialized:', cart);
        }
        console.log('Cart from cookie:', cart);

    </script>
</head>

<body>
    {% include 'navbar.html' %}
    <hr>
    <div class="container">
        {% block content %}

        {% endblock content %}
    </div>
    <script src="{% static 'js/cart.js' %}"></script>
</body>

</html>

myapp/templates/myapp/cart.html
{% extends 'main.html' %}
{% load static %}
{% block title %}
cart
{% endblock title %}

{% block content %}
<div class="container my-5">
    <!-- Header -->
    <div
        class="d-flex flex-column flex-md-row justify-content-between align-items-start align-items-md-center mb-4 gap-3">
        <h2 class="fw-bold mb-0">Your Shopping Cart : <span>{{total_quantity}}</span> <small>items</small></h2>
        <a href="{% url 'myapp:store' %}" class="btn btn-outline-info btn-lg">
            Continue Shopping
        </a>
    </div>

    <!-- Table Wrapper -->
    <div class="table-responsive shadow-sm rounded-3">
        <table class="table table-bordered table-hover align-middle mb-0">
            <thead class="table-light">
                <tr>
                    <th scope="col">Product Image</th>
                    <th scope="col">Price</th>
                    <th scope="col">Quantity</th>
                    <th scope="col">Total</th>
                    <th scope="col">
                        <a href="{% url 'myapp:checkout' %}" class="btn btn-sm btn-danger">
                            Checkout
                        </a>
                    </th>
                </tr>
            </thead>
            <tbody>


                {% for item in order_items %}




                <tr>
                    <td class="text-center">
                        <img src="{{item.product.imageUrl}}" alt="{{ item.product.name }}" class="img-thumbnail rounded"
                            style="width: 60px; height: 60px; object-fit: cover;">
                    </td>

                    <td>${{ item.product.price }}</td>
                    <td>
                        <div class="d-flex flex-column align-items-center">
                            <span class="fw-semibold fs-5">{{ item.quantity }}</span>
                            <div class="d-flex flex-column mt-2">

                                <img class="updateCart" data-action="add" data-product="{{item.product.id}}"
                                    src="{% static 'images/errowup.png' %}" alt="Increase"
                                    style="width: 20px; height: 20px;">


                                <img data-action="remove" data-product="{{item.product.id}}" class="updateCart"
                                    src="{% static 'images/errowd.png' %}" alt="Decrease"
                                    style="width: 20px; height: 20px;">

                            </div>
                        </div>
                    </td>

                    <td>${{ item.total_price }}</td>
                    <td></td>
                </tr>


                {% endfor %}




            </tbody>
        </table>
    </div>

    <!-- Summary -->
    <div
        class="d-flex flex-column flex-md-row justify-content-between align-items-start align-items-md-center mt-4 gap-3">
        <h4 class="fw-semibold text-dark mb-0">Total: ${{ total_price }}</h4>
        <a href="{% url 'myapp:checkout' %}" class="btn btn-primary btn-lg">
            Proceed to Checkout
        </a>
    </div>
</div>



{% endblock content %}

myapp/templates/myapp/checkout.html
{% extends 'main.html' %}
{% load static %}
{% block title %}
Checkout
{% endblock title %}

{% block content %}
<div class="row">
    <div class="col-lg-6">
        <form method="POST" class="form" action="">
            {% csrf_token %}

            <!-- Customer Details -->
            <div class="row g-3">
                <div class="Customer-infor">
                    <div class="col-md-6">
                        <label for="username" class="form-label">User Name</label>
                        <input type="text" class="form-control" id="username" name="username" required>
                    </div>

                    <div class="col-md-6">
                        <label for="email" class="form-label">Email Address</label>
                        <input type="email" class="form-control" id="email" name="email" required>
                    </div>
                    <div class="col-md-6">
                        <label for="phone" class="form-label">Phone Number</label>
                        <input type="tel" class="form-control" id="phone" name="phone" required>
                    </div>
                </div>


                <!-- Shipping Address -->
                <div class="shipping-infor">
                    <div class="col-md-6">
                        <label for="address" class="form-label">Shipping Address</label>
                        <input type="text" class="form-control" id="address" name="address"
                            placeholder="Street, City, Region" required>
                    </div>

                    <div class="col-md-6">
                        <label for="zip_code" class="form-label">ZIP / Postal Code</label>
                        <input type="text" class="form-control" id="zip_code" name="zip_code"
                            placeholder="ZIP / Postal Code" required>
                    </div>
                    <div class="col-md-6">
                        <label for="state" class="form-label">State</label>
                        <input type="text" class="form-control" placeholder="Your state" id="state" name="state"
                            required>
                    </div>
                    <div class="col-md-6">
                        <label for="country" class="form-label">Country</label>
                        <input type="text" class="form-control" placeholder="Country" id="country" name="country"
                            required>
                    </div>

                </div>

            </div>
            <!-- Submit Button -->

            {% if total_price > 0 %}
            <div class="mt-4  submit-form-btn">
                <button type="submit" class="btn btn-success btn-lg w-100">Continue</button>
            </div>
            {% endif %}


        </form>
        <div class="mt-4 btn btn-success btn-lg w-100 paypal" hidden>
            <small>Paypal Options</small>
            <button class="btn btn-outline-info btn-lg w-100">Make payments</button>
        </div>
    </div>



    <div class="col-lg-6">
        <a href="{% url 'myapp:cart' %}" class="btn btn-lg btn-outline-info">back to card</a>
        <!-- Order Summary -->
        <h4 class="fw-semibold mb-4">Order Summary</h4>
        <p class="text-muted">Please review your order details before proceeding.</p>
        <table class="table table-bordered align-middle">
            <thead>
                <tr>
                    <th scope="col">Product</th>
                    <th scope="col">Price</th>
                    <th scope="col">Quantity</th>
                    <th scope="col">Total</th>
                </tr>
            </thead>
            <tbody>

                {% for item in order_items %}




                <tr>
                    <td class="text-center">
                        <img src="{{item.product.imageUrl}}" alt="{{ item.product.name }}" class="img-thumbnail rounded"
                            style="width: 60px; height: 60px; object-fit: cover;">
                    </td>

                    <td>${{ item.product.price }}</td>
                    <td>
                        {{ item.quantity }}
                    </td>

                    <td>${{ item.total_price }}</td>

                </tr>


                {% endfor %}

            </tbody>
        </table>

        <!-- Total Price -->
        <h5 class="fw-semibold text-end">Total: ${{ total_price }}</h5>
    </div>
</div>

<script>
    const shipping = '{{shipping|lower}}';
    console.log('shipping is not digital', shipping);
    if (shipping === 'false') {
        document.querySelector('.shipping-infor').innerHTML = '';
    }

    if (user !== 'AnonymousUser') {
        document.querySelector('.Customer-infor').innerHTML = '';
    }

    const form = document.querySelector('.form');
    form.onsubmit = function (e) {
        e.preventDefault()
        document.querySelector('.paypal').hidden = false;
        document.querySelector('.submit-form-btn').hidden = true;
    }
    document.querySelector('.paypal').addEventListener('click', function () {
        submitData()
    })

    const submitData = () => {

        let total = '{{total_price}}'
        console.log('total', total)
        let userData = {
            'username': '',
            'email': '',
            'phone': '',
            'total_price': total,

        }
        if (user === 'AnonymousUser') {

            userData.username = form.username.value
            userData.email = form.email.value
            userData.phone = form.phone.value
        }

        console.log('data submited..', userData)
        let shippingData = {
            'address': '',
            'state': '',
            'zip_code': '',
            'country': '',
        }
        console.log('shipping data', shippingData)

        if (shipping === 'true') {
            shippingData.address = form.address.value
            shippingData.state = form.state.value
            shippingData.zip_code = form.zip_code.value
            shippingData.country = form.country.value
        }

        const url = '/process-order/'
        fetch(url, {
            method: 'POST',
            headers: {
                'Content-Type': 'application/json',
                'X-CSRFToken': csrftoken
            },
            body: JSON.stringify({
                'form': userData, 'shipping-data': shippingData
            })
        })
            .then(resp => resp.json())
            .then(data => {
                console.log(data)
                window.location.href = "{% url 'myapp:store' %}"
            })
            .catch(Error => console.log(Error))
    }
</script>

{% endblock content %}

myapp/templates/myapp/store.html
{% extends 'main.html' %}
{% load static %}
{% block title %}
Store
{% endblock title %}

{% block content %}
<div class="row my-4">

    {% for product in products %}
    <div class="col-md-4 mt-3">
        <div class="card h-100 shadow-sm border-0 rounded-4 d-flex flex-column">
            <!-- Product Image -->

            {% if product.image %}
            <img src="{{product.imageUrl}}" class="card-img-top rounded-top-4 img-fluid object-fit-cover"
                style="height: 200px;" alt="Product Image">

            {% else %}
            <img src="{% static 'images/no-image.png' %}" class="card-img-top rounded-top-4 img-fluid object-fit-cover"
                style="height: 200px;" alt="Product Image">
            {% endif %}



            <!-- Card Body -->
            <div class="card-body d-flex flex-column">
                <!-- Title -->
                <h5 class="card-title fw-bold mb-2">{{product.name}}</h5>

                <!-- Price -->
                <p class="text-success fw-semibold fs-5 mb-3">${{product.price}}</p>

                <!-- Add to Cart Button -->
                <button data-product="{{product.id}}" data-action="add"
                    class="btn btn-outline-success w-100 mb-2 updateCart">Add to
                    Cart</button>

                <!-- View Button pushed to bottom -->
                <div class="mt-auto">
                    <a href="#" class="btn btn-primary w-100">View Details</a>
                </div>
            </div>
        </div>
    </div>

    {% endfor %}




</div>



{% endblock content %}

myapp/templates/navbar.html
{% load static %}

<nav class="navbar navbar-expand-lg bg-info navbar-infor">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'myapp:store' %}">E-cormmenrce</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'myapp:store' %}">E cormmerce</a>
                </li>

            </ul>
            <div class="form-initial d-flex align-items-center gap-3 my-2 my-lg-0">
                <!-- Login Button -->
                <a class="btn btn-outline-success px-4" href="#">Login</a>

                <!-- Cart Item Count -->
                <span id="total_quantity" class="text-success fw-bold fs-5">{{total_quantity|default:0}}</span>

                <!-- Cart Icon Button -->
                <a class="btn btn-outline-success d-flex align-items-center justify-content-center p-2"
                    href="{% url 'myapp:cart' %}">
                    <img src="{% static 'images/cart.jpeg' %}" alt="cart-icon" style="width: 30px; height: 30px;">
                </a>
            </div>

        </div>
    </div>
</nav>